packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  node: set this to true or false
  prisma: true
  unrs-resolver: true
  workerd: true
